# Generated by Django 2.2.28 on 2022-11-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressdwvkpcluvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdwvkpcluvm',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
